/**
 * Central export for all stores
 */

export {
	catalogsStore,
	activeCategoryStore,
	activeCatalogStore,
	selectedRecipeStore,
	selectedRecipesByCategoryStore,
	searchTextStore,
	searchTextByCategoryStore,
	showOnlyFavoritesStore,
	favoritesStore,
	filteredRecipesStore,
	setActiveCategory,
} from "./recipes.js";

export {
	inventoryStore,
	inventoryLoadingStore,
	initInventory,
	getInventoryQuantity,
	setInventoryQuantity,
	addToInventory,
	consumeFromInventory,
	clearInventory,
	getInventoryItems,
	exportInventoryToCSV,
	importInventoryFromCSV,
} from "./inventory.js";

export {
	settingsStore,
	settingsLoadingStore,
	initSettings,
	updateSetting,
	setTransparency,
	setCookingMastery,
	setAlchemyMastery,
	setCookingTotalMastery,
	setAlchemyTotalMastery,
	addFavorite,
	removeFavorite,
	toggleFavorite as toggleSettingsFavorite,
	isFavorite,
	setServerRegion,
	setTheme,
	saveWindowState,
	setBossSoundEnabled,
	setTimerSoundEnabled,
	setBossAlertMinutes,
	setFontBold,
	setFontSize,
	setBarterLevel,
	setValuePack,
	setAlwaysOnTop,
	setAnimationsEnabled,
	toggleBossHidden,
	setHiddenBosses,
} from "./settings.js";

export { appVersionStore, initAppVersion } from "./app-version.js";

export type { AppTheme, FontFamily, FontSize, WindowState } from "$lib/services/persistence";

export {
	craftingLogStore,
	craftingLogLoadingStore,
	loadCraftingLog,
	addCraftingSession,
	deleteCraftingSession,
	clearCraftingLog,
	getCraftingStats,
	type CraftingSession,
} from "./crafting-log.js";

export {
	timerStore,
	timerDisplay,
	timerProgress,
	isTimerActive,
	setTimerMinutes,
	setTimerSeconds,
	setTimerPreset,
	startTimer,
	pauseTimer,
	resumeTimer,
	stopTimer,
	resetTimer,
	cleanupTimer,
	type TimerState,
} from "./timer.js";

export {
	viewModeStore,
	activeTabStore,
	clickThroughStore,
	cycleViewMode,
	setViewMode,
	type ViewMode,
	type ActiveTab,
} from "./view-mode.js";

export {
	tickStore,
	startBossTimer,
	stopBossTimer,
	nextBossSpawns,
	nextBossSpawn,
	nextBossCountdown,
	nextBossNames,
	formatCountdown,
	formatSpawnTime,
	formatElapsed,
	getBossNames,
	previousBossSpawn,
	previousBossElapsed,
	previousBossNames,
	type NextBossInfo,
	type PreviousBossInfo,
} from "./boss-timer.js";

export {
	barterSubTabStore,
	logSubTabStore,
	logCraftingSearchStore,
	logCraftingCategoryStore,
	logGrindingSearchStore,
	logHuntingSearchStore,
	settingsTabStore,
	type BarterSubTab,
	type LogSubTab,
	type LogCategoryFilter,
	type SettingsTab,
} from "./ui-state.js";

export {
	recipeIndexStore,
	allRecipesStore,
	plannerPlansStore,
	activePlanIdStore,
	activePlanStore,
	inventoryAwareStore,
	plannerViewStore,
	plannerExpandedNodesStore,
	plannerRecipeSearchStore,
	navigateToRecipeStore,
	plannerTreeStore,
	shoppingListStore,
	craftingStepsStore,
	createPlan,
	deletePlan,
	setActivePlan,
	setGoalQuantity,
	toggleStep,
	loadPlannerData,
	getExpandedSet,
	setExpandedSet,
	toggleExpanded,
	type RecipeIndexEntry,
	type PlannerView,
} from "./planner.js";

export {
	announcementsStore,
	announcementsLoadingStore,
	announcementsFetchErrorStore,
	currentCardIndexStore,
	updateAvailableStore,
	activeMessagesStore,
	initAnnouncements,
	fetchAnnouncements,
	startAnnouncementPolling,
	stopAnnouncementPolling,
	dismissMessage,
	nextCard,
	getDownloadUrl,
	compareVersions,
} from "./announcements.js";

export {
	toastStore,
	showToast,
	dismissToast,
	type Toast,
	type ToastType,
} from "./toast.js";

export {
	grindingDataStore,
	grindingDataLoadingStore,
	loadGrindingData,
	grindingSearchStore,
	selectedSpotStore,
	filteredSpotsStore,
	selectedSpotItems,
	selectSpot,
	clearSpot,
	lootCountsStore,
	lootValuesStore,
	incrementLoot,
	setLootCount,
	setLootValue,
	resetLootCounts,
	totalLootCount,
	totalLootValue,
	marketPricesLoadingStore,
	fetchMarketPrices,
	grindingTimerStore,
	grindingTimerDisplay,
	grindingTimerProgress,
	setGrindingTimerMinutes,
	setGrindingTimerSeconds,
	setGrindingTimerPreset,
	startGrindingTimer,
	pauseGrindingTimer,
	resumeGrindingTimer,
	stopGrindingTimer,
	resetGrindingTimer,
	cleanupGrindingTimer,
	endGrindingSession,
	grindingLogStore,
	grindingLogLoadingStore,
	loadGrindingLog,
	deleteGrindingSession,
	clearGrindingLog,
	getGrindingStats,
	type GrindingSpot,
	type GrindingItem,
	type GrindingSession,
	type GrindingLootEntry,
	type GrindingTimerState,
} from "./grinding.js";

export {
	dashboardTimeRangeStore,
	dashboardTabStore,
	getDashboardSummary,
	getActivityBreakdown,
	getProfitOverTime,
	getTopItems,
	getRecentSessions,
	getSpotBreakdown,
	getCumulativeSilver,
	type TimeRange,
	type ActivityType,
	type DashboardTab,
	type DashboardSummary,
	type ActivityBreakdown,
	type ProfitDataPoint,
	type ItemAcquisition,
	type UnifiedSession,
	type SpotBreakdown,
} from "./dashboard.js";

export {
	huntingDataStore,
	huntingDataLoadingStore,
	loadHuntingData,
	huntingSearchStore,
	huntingSelectedSpotStore,
	huntingFilteredSpotsStore,
	huntingSelectedSpotItems,
	selectHuntingSpot,
	clearHuntingSpot,
	huntingLootCountsStore,
	huntingLootValuesStore,
	setHuntingLootCount,
	setHuntingLootValue,
	resetHuntingLootCounts,
	huntingTotalLootCount,
	huntingTotalLootValue,
	huntingMarketPricesLoadingStore,
	fetchHuntingMarketPrices,
	huntingLogStore,
	huntingLogLoadingStore,
	loadHuntingLog,
	endHuntingSession,
	deleteHuntingSession,
	clearHuntingLog,
	getHuntingStats,
	EQUIPMENT_TIERS,
	type HuntingSpot,
	type HuntingItem,
	type HuntingSession,
	type HuntingLootEntry,
} from "./hunting.js";

export {
	barterDraftStore,
	resetBarterDraft,
	type BarterDraft,
	type BarterDraftEntry,
	barterItemsStore,
	barterItemsLoadingStore,
	parleyMasteryStore,
	loadBarterData,
	getItemsByTier,
	barterInventoryStore,
	barterInventoryLoadingStore,
	loadBarterInventory,
	updateBarterItemQuantity,
	setCrowCoins,
	barterLogStore,
	barterLogLoadingStore,
	loadBarterLog,
	logBarterSession,
	deleteBarterSession,
	clearBarterLog,
	shipUpgradesStore,
	shipStatsStore,
	shipProgressStore,
	shipProgressLoadingStore,
	loadShipData,
	loadShipProgress,
	updateShipMaterial,
	toggleShipStage,
	sailorRosterStore,
	sailorRosterLoadingStore,
	loadSailorRoster,
	addSailor,
	updateSailor,
	removeSailor,
} from "./bartering.js";

export {
	treasureDataStore,
	treasureDataLoadingStore,
	loadTreasureData,
	treasureProgressStore,
	treasureProgressLoadingStore,
	loadTreasureProgress,
	markPieceObtained,
	unmarkPieceObtained,
	setHoursSpent,
	type TreasurePiece,
	type TreasureDefinition,
	type TreasuresData,
	type PieceProgress,
	type TreasureProgressData,
} from "./treasure.js";

export {
	weeklyTasksDataStore,
	loadWeeklyTasksData,
	weeklyTasksProgressStore,
	loadWeeklyTasksProgress,
	setHighestStage,
	toggleCompletedThisWeek,
	markFirstClear,
	unmarkFirstClear,
} from "./weekly-tasks.js";
