/**
 * Central export for all stores
 */

export {
	catalogsStore,
	activeCategoryStore,
	activeCatalogStore,
	selectedRecipeStore,
	selectedRecipesByCategoryStore,
	searchTextStore,
	searchTextByCategoryStore,
	showOnlyFavoritesStore,
	favoritesStore,
	filteredRecipesStore,
	setActiveCategory,
} from "./recipes.js";

export {
	inventoryStore,
	inventoryLoadingStore,
	initInventory,
	getInventoryQuantity,
	setInventoryQuantity,
	addToInventory,
	consumeFromInventory,
	clearInventory,
	getInventoryItems,
	exportInventoryToCSV,
	importInventoryFromCSV,
} from "./inventory.js";

export {
	settingsStore,
	settingsLoadingStore,
	initSettings,
	updateSetting,
	setTransparency,
	setCookingTotalMastery,
	setAlchemyTotalMastery,
	addFavorite,
	removeFavorite,
	toggleFavorite as toggleSettingsFavorite,
	isFavorite,
	setServerRegion,
	saveWindowState,
	flushSettings,
	setBossSoundEnabled,
	setTimerSoundEnabled,
	setBossAlertMinutes,
	setBossSoundCustomName,
	setFontBold,
	setFontSize,
	setBarterLevel,
	setValuePack,
	setAlwaysOnTop,
	setMarketRegion,
	setMiniShowClocks,
	setClockFormat24h,
	setLocale,
	toggleBossHidden,
	setHiddenBosses,
} from "./settings.js";

export { appVersionStore, initAppVersion } from "./app-version.js";

export type { FontFamily, FontSize, Locale, WindowState } from "$lib/services/persistence";

export {
	notesStore,
	noteCategoriesStore,
	notesLoadingStore,
	loadNotesData,
	initNotesSync,
	flushNotes,
	setReminderFireCallback,
	startReminderTick,
	stopReminderTick,
} from "./notes.js";

export {
	craftingLogStore,
	craftingLogLoadingStore,
	loadCraftingLog,
	addCraftingSession,
	deleteCraftingSession,
	clearCraftingLog,
	getCraftingStats,
	type CraftingSession,
} from "./crafting-log.js";

export {
	viewModeStore,
	activeTabStore,
	clickThroughStore,
	setViewMode,
	type ViewMode,
	type ActiveTab,
} from "./view-mode.js";

export {
	tickStore,
	startBossTimer,
	stopBossTimer,
	nextBossSpawns,
	nextBossSpawn,
	nextBossCountdown,
	nextBossNames,
	formatCountdown,
	formatSpawnTime,
	formatElapsed,
	getBossNames,
	previousBossSpawn,
	previousBossElapsed,
	previousBossNames,
	type NextBossInfo,
	type PreviousBossInfo,
} from "./boss-timer.js";

export {
	barterSubTabStore,
	logSubTabStore,
	logCraftingSearchStore,
	logCraftingCategoryStore,
	logGrindingSearchStore,
	logHuntingSearchStore,
	settingsTabStore,
	lootHideUnmatchedStore,
	lootSourceFilterStore,
	lootScanLogFilterStore,
	lootScanLogGroupedStore,
	lootFocusInGameStore,
	lootSubTabStore,
	lootLogDetailIdStore,
	lootLogsRangeStore,
	type LootScanLogFilter,
	type BarterSubTab,
	type LogSubTab,
	type LogCategoryFilter,
	type SettingsTab,
	type LootSubTab,
	type LootLogsRange,
} from "./ui-state.js";

export {
	recipeIndexStore,
	allRecipesStore,
	plannerPlansStore,
	activePlanIdStore,
	activePlanStore,
	inventoryAwareStore,
	plannerViewStore,
	plannerExpandedNodesStore,
	plannerRecipeSearchStore,
	navigateToRecipeStore,
	plannerTreeStore,
	shoppingListStore,
	craftingStepsStore,
	createPlan,
	deletePlan,
	setActivePlan,
	setGoalQuantity,
	toggleStep,
	loadPlannerData,
	getExpandedSet,
	setExpandedSet,
	toggleExpanded,
	type RecipeIndexEntry,
	type PlannerView,
} from "./planner.js";

export {
	toastStore,
	showToast,
	dismissToast,
	type Toast,
	type ToastType,
} from "./toast.js";

export {
	grindingDataStore,
	grindingDataLoadingStore,
	loadGrindingData,
	grindingSearchStore,
	selectedSpotStore,
	filteredSpotsStore,
	selectedSpotItems,
	selectSpot,
	clearSpot,
	lootCountsStore,
	lootValuesStore,
	incrementLoot,
	setLootCount,
	setLootValue,
	resetLootCounts,
	totalLootCount,
	totalLootValue,
	marketPricesLoadingStore,
	fetchMarketPrices,
	grindingTimerStore,
	grindingTimerDisplay,
	grindingTimerProgress,
	setGrindingTimerMinutes,
	setGrindingTimerSeconds,
	setGrindingTimerPreset,
	startGrindingTimer,
	pauseGrindingTimer,
	resumeGrindingTimer,
	stopGrindingTimer,
	resetGrindingTimer,
	cleanupGrindingTimer,
	endGrindingSession,
	grindingLogStore,
	grindingLogLoadingStore,
	loadGrindingLog,
	deleteGrindingSession,
	clearGrindingLog,
	getGrindingStats,
	type GrindingSpot,
	type GrindingItem,
	type GrindingSession,
	type GrindingLootEntry,
	type GrindingTimerState,
} from "./grinding.js";

export {
	dashboardTimeRangeStore,
	dashboardTabStore,
	getDashboardSummary,
	getActivityBreakdown,
	getProfitOverTime,
	getTopItems,
	getRecentSessions,
	getSpotBreakdown,
	getCumulativeSilver,
	type TimeRange,
	type ActivityType,
	type DashboardTab,
	type DashboardSummary,
	type ActivityBreakdown,
	type ProfitDataPoint,
	type ItemAcquisition,
	type UnifiedSession,
	type SpotBreakdown,
} from "./dashboard.js";

export {
	huntingDataStore,
	huntingDataLoadingStore,
	loadHuntingData,
	huntingSearchStore,
	huntingSelectedSpotStore,
	huntingFilteredSpotsStore,
	huntingSelectedSpotItems,
	selectHuntingSpot,
	clearHuntingSpot,
	huntingLootCountsStore,
	huntingLootValuesStore,
	setHuntingLootCount,
	setHuntingLootValue,
	resetHuntingLootCounts,
	huntingTotalLootCount,
	huntingTotalLootValue,
	huntingMarketPricesLoadingStore,
	fetchHuntingMarketPrices,
	huntingLogStore,
	huntingLogLoadingStore,
	loadHuntingLog,
	endHuntingSession,
	deleteHuntingSession,
	clearHuntingLog,
	getHuntingStats,
	EQUIPMENT_TIERS,
	type HuntingSpot,
	type HuntingItem,
	type HuntingSession,
	type HuntingLootEntry,
} from "./hunting.js";

export {
	barterItemsStore,
	barterItemsLoadingStore,
	parleyMasteryStore,
	loadBarterData,
	getItemsByTier,
	barterInventoryStore,
	barterInventoryLoadingStore,
	loadBarterInventory,
	updateBarterItemQuantity,
	setCrowCoins,
	barterLogStore,
	barterLogLoadingStore,
	loadBarterLog,
	logBarterSession,
	deleteBarterSession,
	clearBarterLog,
	shipUpgradesStore,
	shipStatsStore,
	shipMaterialRecipesStore,
	shipIngredientsStore,
	updateShipIngredient,
	shipProgressStore,
	shipProgressLoadingStore,
	loadShipData,
	loadShipProgress,
	updateShipMaterial,
	toggleShipStage,
	sailorRosterStore,
	sailorRosterLoadingStore,
	loadSailorRoster,
	addSailor,
	updateSailor,
	removeSailor,
} from "./bartering.js";

export {
	treasureDataStore,
	treasureDataLoadingStore,
	loadTreasureData,
	treasureProgressStore,
	treasureProgressLoadingStore,
	loadTreasureProgress,
	markPieceObtained,
	unmarkPieceObtained,
	setHoursSpent,
	type TreasurePiece,
	type TreasureDefinition,
	type TreasuresData,
	type PieceProgress,
	type TreasureProgressData,
} from "./treasure.js";

export {
	weeklyTasksDataStore,
	loadWeeklyTasksData,
	weeklyTasksProgressStore,
	loadWeeklyTasksProgress,
	setHighestStage,
	toggleCompletedThisWeek,
	markFirstClear,
	unmarkFirstClear,
} from "./weekly-tasks.js";

export {
	lootSettingsStore,
	setLootRegion,
	setLootFreqHz,
	setLootMinConfidence,
	addSavedRegion,
	removeSavedRegion,
	resetLootSettings,
	acknowledgeLootDisclaimer,
	setLootStrictMode,
	setLootColorMask,
	setLootUpscaleFactor,
	setLootTemporalFrames,
	setLootInventoryMergeOnSave,
} from "./loot-settings.js";

export {
	lootCatalogStore,
	lootCatalogLoadingStore,
	getQtyHint,
	getLootExactIndex,
	getCatalogEntry,
	loadLootCatalog,
} from "./loot-catalog.js";

export {
	captureSessionStore,
	cleanupCaptureSession,
	startCaptureSession,
	pauseCaptureSession,
	resumeCaptureSession,
	finalizeCaptureSession,
	mergeMatchedRowsToInventory,
	resetCaptureSession,
	setSessionLabel,
	setSessionRegion,
	applyOcrEvent,
	renameRow,
	setRowCount,
	setRowNote,
	addManualRow,
	deleteRow,
	linkRowToItem,
	unlinkRow,
	unlockRow,
} from "./loot-session.js";

export {
	lootLogsStore,
	lootLogsLoadingStore,
	addLootLog,
	deleteLootLog,
	renameLootLog,
	clearLootLogs,
	getLootLog,
	setLootLogMergedAt,
} from "./loot-logs.js";

export type { CatalogEntry, MatchResult } from "$lib/services/ocr-matcher";

export {
	PARLEY_MAX_DEFAULT,
	islandsDataStore,
	islandsDataLoadingStore,
	loadIslandsData,
	barterMapLayoutStore,
	barterMapLayoutLoadingStore,
	loadBarterMapLayout,
	applyPositionOverride,
	resetPositionOverrides,
	addCustomNode,
	removeCustomNode,
	getEffectiveNode,
	currentRouteStore,
	currentRouteLoadingStore,
	routeTickStore,
	startRouteTicker,
	stopRouteTicker,
	loadCurrentRoute,
	pauseRoute,
	resumeRoute,
	elapsedSeconds,
	addTrade,
	removeTrade,
	clearRoute,
	refillParley,
	getMasteryReduction,
	effectiveParleyCost,
	totalParleySpent,
	findItemsByName,
	lookupTradeDefaults,
	tierDefaultSilver,
	routeLogsStore,
	routeLogsLoadingStore,
	loadRouteLogs,
	migrateLegacyLog,
	finalizeRoute,
	deleteRouteLog,
	clearAllRouteLogs,
	routeEditModeStore,
	routeRegionFocusStore,
	routeOpenNodeStore,
	recentQuickAddChips,
	type AddTradePayload,
	type TradeDefaults,
	type QuickAddChip,
} from "./bartering-routes.js";
